### ISSUE TITLE
Another use case that fails

### ISSUE THREAD

**Issue by Robinlovelace** [osmdatar/osmdata#12]
From the README:

```r
osmcsv <- '[out:csv(::id,::type,"name")];
area[name="Bonn"]->.a;
( node(area.a)[railway=station];
  way(area.a)[railway=station];
  rel(area.a)[railway=station]; );
out;'

obj <- overpass_query(osmcsv)
##  Error in eval(substitute(expr), envir, enclos) : expected < 
```

**Comment by mpadge** [comment]
That's because I've disabled csv output as noted [here](https://github.com/osmdatar/osmdata/issues/1) - this all needs to be considered in the context of [that issue](https://github.com/osmdatar/osmdata/issues/1)
