### ISSUE TITLE
authorship needs tidying

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#15]
Thanks @Robinlovelace for the introduction and hello @masalmon - great to finally e-meet you back. These are two brief Qs I just emailed to you via Robin:

1. You've got an Roxygen field [here](https://github.com/osmdatar/osmdata/blob/master/R/overpass_query.R#L8) that says "@author Maelle Salmon". Are you okay with that line being removed, because:

   i. authorship for individual functions is not general R practice;

   ii. this raises difficult questions of whether anyone else has the right to accept a PR that modifies that function, and what the potential status of your authorship would be thereafter?; and

   iii. You're in the author list in DESCRIPTION anyway

You can have an additional description of what you contributed ([like these](https://github.com/osmdatar/osmdata/blob/master/DESCRIPTION#L9-L14)), but if you're going to be involved further, it'd likely be better and more meaningful to simply list you as a general "author" absent specifications. I'd appreciate an indication of your preference in this regard.

2. Are you okay with the diacritical marks being removed from your name, because CRAN rejects those anyway? (It'll then just become ''Maelle'' - blame ASCII for that, as I'm sure you're well aware.)

**Comment by masalmon** [comment]
Hi @mpadge !

* No problem about erasing my name from the function file! 

* In this DESCRIPTION for instance https://github.com/ropenscilabs/ropenaq/blob/master/DESCRIPTION I have this line `Encoding: UTF-8` at the end and then on CRAN my name is written correctly with the accent https://cran.r-project.org/web/packages/ropenaq/index.html It might create warnings when doing `devtools::release`, but other than that my first name was not a CRAN problem. I'm sorry to make this complicated but well blame my parents :grin:

**Comment by mpadge** [comment]
Thanks Maëlle - all fixed and your proper name reinstated throughout - [it even passes!](https://travis-ci.org/osmdatar/osmdata/builds/179755561).

**Comment by masalmon** [comment]
Thanks a lot! 😸
