### ISSUE TITLE
pipes

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#16]
[This commit](https://github.com/osmdatar/osmdata/commit/d6d976cff62611e7bae42d56a99658d78335be1b) removed most `dplyr` deps, but has left ~~[this one](https://github.com/osmdatar/osmdata/blob/master/R/osmdata-package.R#L57-L61)~~. Once final types & classes are established, try to think of use-cases where pipes would not work anyway to see if this dep is really necessary.
cc @Robinlovelace

**Comment by mpadge** [comment]
`dplyr` dep removed with [this commit](https://github.com/osmdatar/osmdata/commit/7d6ef0267eedb631f406586817bb54d4ea429489).

This issue will be kept open until we know whether `osmdata` functionality may *not* be compatible with pipes, in which case it might be necessary to reinstate the dep (via the much more lightweight `magrittr` of course).

@Robinlovelace - Now do your best and break it!

**Comment by Robinlovelace** [comment]
Just to clarify, now that we don't have a pipe, the mission is to see if it works after

```r
library(magrittr)
```

then

```r
some_osmdata_function(...) %>%
  some_other_osmdatafunction(...)
```

Realised it's got my name on it and I've been slacking!

**Comment by mpadge** [comment]
Yep, that's the mission alright. Your input would be much appreciated!

**Comment by Robinlovelace** [comment]
OK - plan to do in the WIP vignette - would involve adding `magrittr` as a suggest though, if you're up for that?

**Comment by Robinlovelace** [comment]
I've been using pipes a fair amount on the CyIPT project and no issues encounters. What I have encountered, though, is that it would be very useful to represent a multi-criteria query in a single text text string. Will open a new issue on that now.
