### ISSUE TITLE
recursion operator

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#18]
As discussed in [this comment regarding `sf`](https://github.com/osmdatar/osmdata/issues/17#issuecomment-264180761), it would likely be very useful to have some kind of recursion operator for `osmdata`, along the lines of
```
> get_points (osmdat$osm_lines)
```
to return **all data** for all points comprising those lines, including additional `key-val` pairs for the points. This is an implicit [''recursion down''](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_down_.28.3E.29) operator. An analogous [''recursion up''](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_up_.28.3C.29) operator would be
```
> get_lines (osmdat$osm_points)
```
which would return all lines which contain those points. 

A question worth thinking about:
* Are then any instances in which the recursion direction would not be obvious?

If no, then only three functions need be written, for `lines`, `points`, and `polygons`.

**Comment by mpadge** [comment]
Note that horizontal 'recursion' is also possible, for example, through requesting all lines that include any elements present in a given set of lines. This should nevertheless be possible with
```
get_lines (osmdat$osm_lines)
```
although that might need some explaining to clarify why that might be useful.

**Comment by Robinlovelace** [comment]
That would indeed be cool. Perhaps some of the code in **osmar** could help thinking about this, e.g. `find_down()`: https://github.com/cran/osmar/blob/master/R/osmar-finding.R#L170

**Comment by mpadge** [comment]
[issue done](https://github.com/osmdatar/osmdata/blob/master/R/osm_extract.R) with the functions `osm_points`, `osm_lines`, `osm_polygons`, `osm_multilines`, and `osm_multipolygons`
