### ISSUE TITLE
Including sf for benchmarking

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#19]
@Robinlovelace I've now included [this benchmarking file](https://github.com/osmdatar/osmdata/blob/master/tests/timing-benchmark.R), but with the `sf` code commented out. Travis fails otherwise ([see here](https://travis-ci.org/osmdatar/osmdata/builds/181919197)) because `sf` requires [all of this pre-install stuff](https://github.com/edzer/sfr/blob/master/.travis.yml). We can easily put that in later, but in the meantime to keep our travis build times relatively short, we can do without it. This issue is just a flag to fix that up later.

**Comment by Robinlovelace** [comment]
Happy with that - we can uncomment to test locally.

Hopefully eventually SF will work with the 'out of the box' version of GDAL on Ubuntu, perhaps in 17.04?
