### ISSUE TITLE
Rewrite .osm XML parser

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#21]
`osmdata` currently uses the generic `rapidxml` parser. Write a dedicated parser to [speed things up](https://github.com/osmdatar/osmdata/wiki/Timing-benchmarks).

**Comment by mpadge** [comment]
... although `kcachegrind` seems to suggest that most of the processing is in [`_dl_runtime_resolve_avx`](https://sourceware.org/bugzilla/show_bug.cgi?id=20508) - maybe the slowness is just a consequence of my using X86-64 proessors? This ['transition penalty'](https://sourceware.org/bugzilla/show_bug.cgi?id=20508) seems to occupy around 10 times as much processing time as `rcpp_get_osmdata` itself, and within the latter, `traverseWays` takes most of the time. So all seems actually okay, and I just have to resolve this `dl_runtime_resolve` issue...

**Comment by Robinlovelace** [comment]
Over my head mate. Good luck with it though!

**Comment by mpadge** [comment]
Yeah, it's mostly just flags for me. That guff suggests that the slowness is due to some internal X86-64 architecture issue - 90% of the execution is spent in the `rapidxml` parser, where data are constantly swapped between 256- and 512-bit registers. This nevertheless suggests that an apple, for example, would behave totally differently. Don't suppose you've got access to one? If so, please try running  [`tests/timing-benchark.R`](https://github.com/osmdatar/osmdata/blob/master/tests/timing-benchmark.R) on that!

**Comment by Robinlovelace** [comment]
Yes I've access to an apple, thanks to @gawbul who's sat in the same megaoffice as me!

**Comment by gawbul** [comment]
No problem, will help with any benchmarks you need. I know from past experience that using Libxml2 has shown huge speedups in XML parsing for me.

Just having a go at installing now. Currently getting the following:

```
> devtools::install_github("osmdatar/osmdata")
Downloading GitHub repo osmdatar/osmdata@master
from URL https://api.github.com/repos/osmdatar/osmdata/zipball/master


Installing osmdata
'/usr/local/Cellar/r/3.3.2/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/mn/f7_ccrgj3djbm4kx54k3r6n40000gn/T/RtmpWbDj7u/devtools2f9c983c75c/osmdatar-osmdata-9a8b9d3'  \
  --library='/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library'  \
  --install-tests

* installing *source* package ‘osmdata’ ...
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG -fprofile-arcs -ftest-coverage -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I"/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=c++11 -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG -fprofile-arcs -ftest-coverage -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I"/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -g -O2 -c common.cpp -o common.o
clang++ -std=c++11 -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG -fprofile-arcs -ftest-coverage -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I"/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -g -O2 -c get-bbox.cpp -o get-bbox.o
clang++ -std=c++11 -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG -fprofile-arcs -ftest-coverage -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I"/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -g -O2 -c get-osmdata.cpp -o get-osmdata.o
clang++ -std=c++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -L/usr/local/Cellar/r/3.3.2/R.framework/Resources/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o osmdata.so RcppExports.o common.o get-bbox.o get-osmdata.o -lgcov -F/usr/local/Cellar/r/3.3.2/R.framework/.. -framework R -lintl -Wl,-framework -Wl,CoreFoundation
ld: library not found for -lgcov
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [osmdata.so] Error 1
ERROR: compilation failed for package ‘osmdata’
* removing ‘/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/osmdata’
Error: Command failed (1)
```

`ld` isn't able to link using `-lgcov` I think its because my default compiler is `clang++` or perhaps my Xcode version - will try using `g++` instead.

**Comment by mpadge** [comment]
You can also just replace [both of these lines](https://github.com/osmdatar/osmdata/blob/master/configure#L1-L2) with empty `""` because that's all just code coverage stuff.

**Comment by gawbul** [comment]
Sticking this in `~/.R/Makevars` should work shouldn't it?

```
PKG_CXXFLAGS=""
PKG_LIBS=""
```

**Comment by gawbul** [comment]
It did... getting this now though:

```
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/osmdata/libs/osmdata.so':
  dlopen(/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/osmdata/libs/osmdata.so, 6): Symbol not found: _llvm_gcda_emit_arcs
  Referenced from: /usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/osmdata/libs/osmdata.so
  Expected in: flat namespace
 in /usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/osmdata/libs/osmdata.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/Cellar/r/3.3.2/R.framework/Versions/3.3/Resources/library/osmdata’
Error: Command failed (1)
```

Got to nip out for a bit now... seems to be something to do with llvm compiler? Will have a look after 2:30pm.

**Comment by mpadge** [comment]
That's coz of the compiled symbols in the .gcda files. Just clear all /src files except .h, .cop, and makevars and you should be right

**Comment by gawbul** [comment]
Yeah, good point! That worked! Might be worth appending `src/*.o src/*.gcno` to the `rm -rf` statement in the makefile's clean target to automate that when cleaning?

So, under OS X, I needed to either change to using `CXX=g++-6` to work with `-lgcov`, or comment out  `PKG_CXXFLAGS` and `PKG_LIBS` altogether, then run `R CMD INSTALL` with the `--no-configure` flag to stop it passing the flags back in.

I had to do `devtools::load_all ('osmdata', export_all=TRUE)` to get it to export all the required functions for `benchmark()`, e.g. `rcpp_get_osmdata`.

I got the following when running `benchmark`, however:

```
> benchmark()
osmdata: Median time =  461.4512  ms

osmdata took  Inf  times longer to extract  Inf  times as much data
```

I noticed that `mt_sf` and `size_sf` were set to `NULL` and the `microbenchmark` code block was commented out, so I uncommented and did a `source('osmdata/tests/timing-benchmark.R')`.

I then hit issues a couple of other issues with `Error in loadNamespace(name) : there is no package called ‘sf’` and subsequently `-----Error: libudunits2.a not found-----` and `configure: error: gdal-config not found or not executable.` when trying to build `sfr`. I fixed by following the instructions here http://www.karambelkar.info/2016/10/gdal-2-on-mac-with-homebrew/ and doing a `brew install udunits`.

Once all that was done, I got the following output:

```
> benchmark()
SF: Median times (in ms) for ( points lines multipolygons other_relations ):
	( 57.32916 58.85638 67.93799 57.23348 ); total =  241.357 
osmdata: Median time =  445.2354  ms

osmdata took  1.844717  times longer to extract  5.053947  times as much data
```

**Comment by Robinlovelace** [comment]
Awesome work, many thanks Steve.

**Comment by mpadge** [comment]
Yeah, thanks for much for the much appreciated help there @gawbul - that means an apple architecture performs pretty much the same after all, which is really helpful to know. It's a fine idea to put the `rm` statements in the makefile too. I'll also check the flags, but they can't be commented out coz they're needed for codecov to be able to get the lists of compiled objects from travis. i'll dig a bit deeper there.

**Comment by mpadge** [comment]
**NOTE**: `rapidxml` header files are full of `assert` statements, which need to be replaced with `throw` statements.

**Comment by Robinlovelace** [comment]
Interesting stuff. Is this something Andrew Smith could help with? Can ask him next time we meet (Thursday likely).

Robin

**Comment by mpadge** [comment]
Yeah, it absolutely is. Only problem is I definitely won't have time for this at the moment, so this issue isn't even part of the current [milestone](https://github.com/osmdatar/osmdata/milestone/1). Andrew could nevertheless have a go if he wants ... let me know what he says.

**Comment by Robinlovelace** [comment]
Heads up @virgesmith - related to our work to explore travel patterns, as we'll probably want to assign to the travel network at some point.

**Comment by mpadge** [comment]
Closing with [this commit](https://github.com/osmdatar/osmdata/commit/e49ab7844d993fd8cb3ef007e35716b831051665) - speed is no issue now, but the `assert` calls had to go because they are not compatible with `Rcpp`

**Comment by Robinlovelace** [comment]
Looks like a sensible set of error messages - @virgesmith has complained about R's lack of good error messages so hopefully [this](https://github.com/osmdatar/osmdata/commit/e49ab7844d993fd8cb3ef007e35716b831051665) will help to improve the average!
