### ISSUE TITLE
sf suggest on travis

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#28]
@edzer Your help would be much appreciated on getting travis to pass with `suggests:sf` on osx as well as linux - my current [`travis.yml` is here](https://github.com/osmdatar/osmdata/blob/master/.travis.yml), with these travis fails for [linux](https://travis-ci.org/osmdatar/osmdata/jobs/188993962) and [osx](https://travis-ci.org/osmdatar/osmdata/jobs/188993963). It'd also be great to load `sf` within a travis container, which would require `sudo:false`. Any assistance greatly appreciated!

**Comment by mpadge** [comment]
I see that Jim Hester is working on your [`.travis.yml`](https://github.com/edzer/sfr/pull/145/files) - maybe some assistance will come from that. How about making a wiki page detailing the necessary `.travis.yml` structure for an `sf` dependency? (Once it's clear how best to do this ...)

**Comment by edzer** [comment]
I think [this](https://github.com/edzer/sfr/blob/460d002b5771d327114144a29061952332f281bc/.travis.yml) was the shortest I could get to, throwing out all the postgis tests.

**Comment by edzer** [comment]
I have no clue about OSX on travis. An alternative is to develop against sf on CRAN.

**Comment by mpadge** [comment]
Thanks @edzer - it all works, [including osx](https://travis-ci.org/osmdatar/osmdata/builds/189466735), which uses binary packages so passes in spite of default GDAL 1.11.5. [`.travis.yml`](https://github.com/osmdatar/osmdata/blob/master/.travis.yml#L19-L22):
```
 - os: osx
   r: release
   disable_homebrew: true
```
Simple. osx has an `osgeo4mac` bundle which should enable GDAL 2.1.2 to be installed, yet [this hangs on the `GDAL make`](https://travis-ci.org/mpadge/sftest/jobs/189347105). Doesn't matter anyway, because there doesn't seem to be a way to get travis to compile packages on `osx`.

I also couldn't get binary packages to work at all on linux because [`r-cran-sf` does not exist](https://travis-ci.org/mpadge/sftest/jobs/189444415), regardless of whether Michael Rutter's PPA [is added](https://travis-ci.org/mpadge/sftest/jobs/189477003) or not.

**Comment by Robinlovelace** [comment]
Great stuff, imagine this will be useful for others.

**Comment by tbuckl** [comment]
@mpadge thanks, this was helpful. thanks. and thanks for posting this to the sf issues, where i found it by searching "travis" under "closed".
