### ISSUE TITLE
tests tests tests!

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#3]
Write them, and consider [this issue](https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460).

**Comment by mpadge** [comment]
First mocked tests [here](https://github.com/osmdatar/osmdata/blob/master/tests/testthat/test-features.R), but there must be a better way to define the return value from `with_mock` other than having to paste wholesale code from the originating function?

**Comment by mpadge** [comment]
@n-s-f Just a expression of gratitude for your excellently programmed [mockery](https://github.com/n-s-f/mockery) package which I've also praised [in this ROpenSci discussion](https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460/7). I've also incorporated your `stub.R` code within this package and acknowledged [your contribution](https://github.com/osmdatar/osmdata/blob/master/DESCRIPTION) - thanks!

@Robinlovelace - you might be interested to see how much cleaner [these tests](https://github.com/osmdatar/osmdata/blob/master/tests/testthat/test-features.R) are using `stub` rather than `with_mock`. This will be the basic structure of all tests from hereon. Any further suggestions appreciated ...

**Comment by n-s-f** [comment]
@mpadge Thanks so much for the kind words! I'm glad you're finding the code useful.

**Comment by mpadge** [comment]
@n-s-f just found about from @sckott about his [webmockr package](https://github.com/ropenscilabs/webmockr). Just in case either of you weren't aware of the other ...

**Comment by n-s-f** [comment]
@mpadge Thanks for the heads up! Hadn't seen it. @sckott, this looks very cool.

**Comment by sckott** [comment]
hi all, webmockr targets mocking http requests, so no overlap i don't think
