### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by masalmon** [osmdatar/osmdata#31]
@mpadge could you go to settings and make sure that the GitHub pages source is set to “master branch /docs folder”.? Thanks!

**Comment by masalmon** [comment]
Oh now I can do this myself, sorry!

**Comment by masalmon** [comment]
Tada! https://osmdatar.github.io/osmdata/

Just the result from `pkgdown::build_site()` so no fancy theme etc. Might be improved later (e.g. having groups of functions in reference, choosing the order of vignettes in articles) but closing this for now.

**Comment by mpadge** [comment]
sweet!

**Comment by masalmon** [comment]
I should add "make the logo present on the website" to the list of things to fix though... so re-opening.

**Comment by mpadge** [comment]
yeah, that'd be grand!

**Comment by masalmon** [comment]
Ok it was actually really easy :see_no_evil: 

I'll have to look into grouping functions to make the reference more useful, so leaving this open after assigning this to myself.

**Comment by masalmon** [comment]
By the way I see there was a mistake in @hrbrmstr's name, corrected in in DESCRIPTION, now correcting it in the website.

**Comment by masalmon** [comment]
@mpadge the figures are not created when knitting the Rmd because they've been saved before. Any reason why you're doing it this way?

I can copy the figures to the docs/ folder if they don't change much but why not re-create them everytime?

**Comment by masalmon** [comment]
I guess it's because of the speed, but in this case the README could actually be quite minimalist since there's an easy accessible vignette with the website that could be linked from the README?

**Comment by mpadge** [comment]
The figs were there to display directly on the github README - there's no other way to do that. Other than that, no reason to have them pre-saved. We'll have to decide how to divide things up between README, vignettes, and the webpage. But feel free in the meantime to simply go ahead and change as you see fit. The README is kinda junk at the moment, so maybe leave that bit for me to put some initial stuff in over the next day or two, and then start re-jigging things.

**Comment by mpadge** [comment]
I neglected to say by the way that the website is awesome! I guess you're absolutely right that pkgdown is the best - i'm mighty impressed and equally grateful.

**Comment by mpadge** [comment]
I also just noticed that the links on the top right of the webpage are wrong - they both link to `osmdatar/osmdatar` instead of `osmdatar/osmdata` - could you please fix those?

Once [milestone#1](https://github.com/osmdatar/osmdata/milestone/1) is done -- notionally in a week's time -- we can start talking about moving it to `ropensci` and be done with the double `osmdata(r)` confusion. It should also be approaching CRAN-readiness ...

**Comment by masalmon** [comment]
It's really easy to use `pkgdown` -- and I want to make it prettier before the rOpenSci submission! 

What would be good groups of functions for the reference? Maybe only these two?

* Prepare a query string (including helper functions for finding features)

* Manage a query (send it, get status)

See what I mean by groups [here](https://dirkschumacher.github.io/ompr/reference/index.html), it makes the reference easier to browse than the current alphabetical order.

Why is `rcpp_osmdata_sp` exported exactly? And same question for `stub`.

**Comment by masalmon** [comment]
Also note that the rOpenSci review process can last a few weeks so I guess the `osmdatar/osmdata` path will be here for a while :wink:

**Comment by mpadge** [comment]
The grouped functions look great, and I'd agree with your proposed grouping. Maybe also one for "additional OSM info" or something, with "available_features" and "available tags".

"rcpp_osmdata_sp" is not exported, but was inadvertently included in the git repo. I've removed that now.

`stub` unfortunately has to be exported for testing purposes - the recent build fails were my trial at not exporting it, as well as exporting it but removing the `man` entry. It unfortunately has to stay. This is nevertheless a temporary solution to be modified in response to appropriate resolution of [this eternal issue](https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460/10). See also #3.

**Comment by masalmon** [comment]
The README of the website still has no pic, I'll wait for your ok for moving stuff out of it / keeping some pics.

Adding the style file was so easy, I love `pkgdown` so much!

**Comment by masalmon** [comment]
Also @mpadge feel free to criticize the reference organization!

**Comment by mpadge** [comment]
@masalmon FYI there are evidently some `UTF-8` issues with your non-standard name [here](https://osmdatar.github.io/osmdata/reference/osmdata.html) - at least in my browser which does have extra `UTF-8` support. I also see dodgy characters in the tab name.

**Comment by mpadge** [comment]
@masalmon I've [updated `_pkgdown.yml`](https://github.com/osmdatar/osmdata/commit/8500fbc2f9e4234e2c740f762f9a265a732ee83a) but can't seem to do a `pkgdown::build_site()` coz of problems with `testthat()` ... can you try re-compiling? I also note that the the current `references` structure does not reflect the order you gave in `_pkgdown.yml` - hopefully just coz you changed that latter without yet re-compling.

**Comment by masalmon** [comment]
Sorry @mpadge for having been MIA, I'll try to re-build the site in the next days! 

I'm looking at an "old" project I'd done with `overpass`, I'm excited to know that next time I do something similar it'll be with `osmdata`!

**Comment by mpadge** [comment]
thanks @masalmon and no worries! No hurry to rebuild either - probably better to wait until vignettes are at least roughly drafted. Robin was going to do that, but he seems to also have gone MIA, so I'll try to get on to it very soon. Other than that, the whole thing is mostly finished, so I reckon I'll do a round of ropensci review, incorporate any suggestions from that, and cran it.

And interestingly, pkgdown killed my entire `R` workflow by installing dev versions of `devtools` and `roxygen2`, both of which had some minor but devastating bugs. The latter is fixed, but [`pkgbuild`](https://github.com/r-pkgs/pkgbuild) (spun off for new devtools) remains broke, so I can't use pkgdown.

One more interesting fact, in case you didn't see it: [`osmdata` is more than 50% faster than `sf/GDAL`](https://github.com/osmdatar/osmdata/wiki/Timing-benchmarks)!!

**Comment by masalmon** [comment]
Ok I will wait then! I'll also have a look at the vignettes since I said I might add an use-case.

Wow this speed is great news, awesome work!

**Comment by mpadge** [comment]
@masalmon a question for you: the package language is now mucked up because of `pkgdown`, although [github linguist](https://github.com/github/linguist) **should** [ignore the `./docs` folder](https://github.com/github/linguist/blob/master/lib/linguist/documentation.yml). I've also put manual overrides in [`.gitattributes`](https://github.com/osmdatar/osmdata/blob/master/.gitattributes), but that doesn't help either. Language is stuck on 88% `.html`. Any ideas how to fix this?

**Comment by masalmon** [comment]
Mmh I actually don't know, are there related issues in `pkgdown` repo?

**Comment by mpadge** [comment]
Nah, it doesn't seem so - it gets only [9% `.html`](https://github.com/hadley/pkgdown), so the linguist `.yml` seems to work there, but not here. No idea why

**Comment by mpadge** [comment]
whoops, sorry @masalmon - it was actually because bob had included `pkgdown` files in overpass. Removing all of those fixed it up - now no `.html` at all on the stats, and 72% `C++`. All good. We could close this issue now, I'd say ...

**Comment by masalmon** [comment]
If you're happy with the looks of the site, I'd say yes you can close the issue. :-)

**Comment by mpadge** [comment]
@masalmon just re-opened this very briefly to ask you a favour - i've moved some wiki files that i had in `/doc` to `/docs/wiki` - can you please try and `pkgbuild` this to make sure it's still okay with these files there?

**Comment by masalmon** [comment]
trying now!

**Comment by masalmon** [comment]
Bug during README preparation by `pkgdown` but I can actually knit the README directly which is weird

**Comment by mpadge** [comment]
Probably because `pkgdown` expects some kind of `RStudio` compatibility, which I can't guarantee coz i don't use `RStudio` at all (hence all the `makefile`s). Feel free to make any `.Rmd` files `RStudio` compatible any time you discover issues like this.

**Comment by masalmon** [comment]
also for the eval=FALSE chunks, how long would it be to really run them?

**Comment by masalmon** [comment]
mmh it doesn't make any sense for me yet, knitting is no problem, only the `pkgdown` thing.

**Comment by mpadge** [comment]
I meant that comment more just as a future reference. As for `eval=FALSE` ... apart from the `devtools::install_github()` bits, that's generally used for code that illustrates steps without actually using results, so setting `eval=TRUE` ought not make any difference except for taking longer. It'll slow down pkg checks considerably without making any difference to results, so there's no real point setting these to `TRUE`.

**Comment by masalmon** [comment]
I don't understand anything with this README issue, I'll just try to build the website without having the README.Rmd, just the README.md

When you used `pkgdown` @mpadge which issues did you have? Not this one?

**Comment by mpadge** [comment]
Nah, it simply didn't work at all, because `devtools::load_all()` failed (and will still fail [until this issue has been fixed](https://github.com/r-pkgs/pkgbuild/pull/1)). How about trying with a generic README.Rmd from a package that works, and then paste in the content? README has to be re-built anyway, so feel free to change any way you have to

**Comment by masalmon** [comment]
Oh I tried erasing nearly all chunks etc and it didn't work :joy: I even changed the header... I'll try again another time but for now I'll use the "delete the README.Rmd" trick.

**Comment by masalmon** [comment]
Oh no even with this the session aborted at some point, no idea at which point in building the website. This is so weird.

**Comment by masalmon** [comment]
If doing R CHECK I get

```r
Quitting from lines 58-59 (osmdata.Rmd) 
Error: processing vignette 'osmdata.Rmd' failed with diagnostics:
Timeout was reached
```

**Comment by masalmon** [comment]
By the way @mpadge I'm sorry to only write list of bugs, this package is good and you did an awesome job!

**Comment by mpadge** [comment]
Thanks Maëlle - i really appreciate your help! It's only going to make the package loads better. This actually seems to be quite a serious problem, so i've moved it to #37. Obviously `pkgdown` won't work until that's solved.

**Comment by Robinlovelace** [comment]
Just to say, after a long stretch in the digital wilderness (you know the story - grant applications, project deadlines): this is looking amazing. Took a look at the website and it's truly inspiring. Great work Maëlle, thanks for picking up my slack ; )

**Comment by masalmon** [comment]
Still getting an error when trying to `pkgdown::build_home()` although I can knit README.Rmd. How weird is this? :cry:

**Comment by masalmon** [comment]
I'm so puzzled. I can knit the vignette @Robinlovelace wrote but if trying `pkgdown::build_article()` the session freezes. I can't build the website because of this and the README issue. R CMD CHECK passes.

@Robinlovelace if trying `pkgdown::build_site()` do you get error?

Is this related to https://github.com/osmdatar/osmdata/issues/46 ? Should I build the package doing something else than R CMD build because of the configure file?

**Comment by Robinlovelace** [comment]
Works @masalmon as illustrated in latest PR.

**Comment by masalmon** [comment]
Mmmh so I guess it's "just" a Windows thing... I'll try to investigate further because it doesn't feel right to not understand why it doesn't work. But I guess it's not _too_ bad since it only affects `pkgdown`...

**Comment by mpadge** [comment]
don't feel bad about not understanding what `pkgdown` is doing. As you know, it literally killed my whole system, and that took me at least a whole day to try to uncover the source of that and fix it.

**Comment by masalmon** [comment]
I still hope I'll be able to find a fix / open an useful issue in a relevant repo one day :-)

**Comment by Robinlovelace** [comment]
You've more than done that in this package alone - you're contributions have revived the project!

**Comment by masalmon** [comment]
thanks both :grin: 

Nonetheless one day I'll understand this whole mess :crossed_fingers:

**Comment by mpadge** [comment]
apart from unresolvable issues beyond our control, it seems that this is now done, so closing.

**Comment by mpadge** [comment]
FYI @masalmon: I managed to get `pkgdown` kinda working in a container so it didn't infect my system, but even then it doesn't exactly behave reliably. It compiles yet seems to ignore a lot of the directives in the `_pkgdown.yml` file, so I had to do some manual tweaking of the resultant `.html` files. The only thing I can't seem to get is the logo on the front page. Could you please tell me how you managed to make that appear?

**Comment by masalmon** [comment]
@mpadge mmmh I think I just had to put the file in the docs/fig/ folder as you did and then I didn't even change the README code (`![](./fig/title.png)`). Doesn't it work? I see you've written docs/fig/title.png, probably by hand? I _think_ we don't need this.

**Comment by mpadge** [comment]
oh, i deleted `fig/title.png` and re-directed the github `README` to `docs/fig/title.png`. I'll revert that.

**Comment by masalmon** [comment]
I hope it works, I had a look at the old versions and really have the impression it was this way it had worked but let's see.

**Comment by mpadge** [comment]
yep, worked a treat - thanks! Other interesting `pkgdown` observations: 

1. Everything is sorted alphabetically by default, including function refs which do not end up in the order they are placed in the `_pkgdown.yml`. I had to do a manual re-sort on the `.html` files to get them back to the `.yml`-specified order.

2. The `\code{}` lines in the titles of all 'extract' functions (like [`osm_points()`](https://github.com/osmdatar/osmdata/blob/master/R/osm-extract.R#L177)) are not transformed to meaningful `html` codes - they just generate junk which is ignored, and all of these functions just become "Extract all" with nothing following. Again, had to manually edit all `.html` files.

No real point opening issues on these, coz I've got two really minor PRs on other Hadley repos that have been sitting there for months - methinks the dude is officially very highly overstretched

**Comment by masalmon** [comment]
I think it might still be worth opening issues but the limiting factor is of course checking there is no current issue dealing with the same thing. I think he works on packages by cycle, maybe there'll be a new `pkgdown` cycle soon. :-)

**Comment by mpadge** [comment]
ha, and look at this extra bit of auto-sorting [here](https://osmdatar.github.io/osmdata/articles/index.html) - now that's just ridiculous! No sorting algorithm in the world ought to do that! Add to the above list:

* The order of vignettes in `/docs/articles/index.html` also has to be manually changed

**Comment by masalmon** [comment]
Well I still think `pkgdown` made our work much easier compared to writing the website entirely by hand ;-)

I still need to take time one day to understand why we get all these problems for `osmdata` (I don't think I experienced them with other packages)

**Comment by mpadge** [comment]
I totaly agree with you, and am hugely grateful for your bringing that to this project - thank you vielen dank merci!

I'm just compiling the list of manual tweaks here for future reference, further including

* Fix `<title>` fields in all vignettes which `pkgdown` generates as this bunch of junk:
```
<title>
<ol style="list-style-type: decimal">
<li>osmdata</li>
</ol> • osmdata</title>
```
when it should be just `<title> osmdata </title>`

**Comment by mpadge** [comment]
The official and more explicit list of necessary manual edits to `.html` files

1. `docs/articles/index.html` - re-order items as specified in `_pkgdown.yml` (that is, `1. osmdata`, then `2. translation ...`)
2. `docs/articles/osmdata.html` - remove extraneous guff from  `<title>` field - it should be `<title> osmdata [0m~@� osmdata</title>`, as can be copied straight from any function ref pages
3. `docs/articles/osm-sf-translation.html` - ditto
4. `docs/references/index.html` - re-order items as specified in `_pkgdown.yml`; re-insert full "Extract all" names; find `osmdata-package` and remove 2 out of 3 `href`fields.
5. For all function def pages in `docs/references`, modify title field as in 2. above
6. Edit all `docs/reference/osm_*.html` pages and re-insert full fields after "Extract all", as described above

**Comment by masalmon** [comment]
:open_mouth:
