### ISSUE TITLE
README

### ISSUE THREAD

**Issue by masalmon** [osmdatar/osmdata#33]
What does `devtools::load_all (".", export_all=FALSE)` do? Is it needed?

**Comment by mpadge** [comment]
Well ... it's how i always load the package. It's not strictly necessary, just easy for me to uncomment and load. I generally treat the `README.Rmd` as a bit of an experimental space, and just try to keep the `.md` clean. This is probably bad practice, right? So yeah, probably should delete that, and then generally clean up the README once `pkgdown` includes the new vignette to link straight to there.

**Comment by masalmon** [comment]
I'd also be in favor of removing the tests from the README since there's continuous integration?

**Comment by mpadge** [comment]
@masalmon README stripped right back now, and directories generally clean. Closing
