### ISSUE TITLE
add examples to R functions

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#35]

**Comment by Robinlovelace** [comment]
I'm up for this.

**Comment by mpadge** [comment]
Sorry to dump more work on you @Robinlovelace , but apart from the vignette, this is the only remaining task, and I am confident that it would be better done by you because all i'll do is instinctively and intrinsically use examples that already work, so will be far less likely to find issues than you will. Do you reckon you'll be able to find time for this?

**Comment by Robinlovelace** [comment]
Yes I'm well up for this and have it pencilled in for after the vignette updates. Thanks for the reminder.

**Comment by mpadge** [comment]
done and closed
