### ISSUE TITLE
fix print method for `osmdata`objects

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#38]
It works okay onscreen, but the vignettes show that having several consecutive `message` lines is not okay. Fix it!

**Comment by Robinlovelace** [comment]
Links to the print issues over at **sf** in some ways. Happy to do some testing on this.

**Comment by mpadge** [comment]
Not even, coz Edzer uses `cat()` on his `print` methods, which is ... certainly not going to be used here!

**Comment by mpadge** [comment]
... fixed now - @Robinlovelace can you just check in the vignettes that print methods work okay - former output was separated into individual `knitr` lines; it should now appear as a single output block. Once you confirm, this can be closed

**Comment by Robinlovelace** [comment]
Confirmed: I think the print method is very neat and informative now, from the vignette:

```
Object of class 'osmdata' with:
                 $bbox : 51.2867602,-0.510375,51.6918741,0.3340155
        $overpass_call : The call submitted to the overpass API
            $timestamp : ##------ Sun Feb 26 21:41:02 2017 ------##
           $osm_points : 'sp' SpatialpointsDataFrame with 4564 points
            $osm_lines : 'sp' SpatiallinesDataFrame with 688 lines
         $osm_polygons : 'sp' SpatialpolygonsDataFrame with 0 polygons
       $osm_multilines : 'sp' SpatialmultilinesDataFrame with 0 multilines
    $osm_multipolygons : 'sp' SpatialmultipolygonsDataFrame with 0 multipolygons
```

**Comment by Robinlovelace** [comment]
One thing that I was wondering though: where can we see the full url string that was queried? That could be a useful thing to store/show. Not a priority though.

**Comment by mpadge** [comment]
Yep: `qry_to_string(q)` returns exactly that. Particularly useful coz it can be pasted directly into overpass turbo

**Comment by mpadge** [comment]
Actually, that should be put in the vignette somewhere!

**Comment by Robinlovelace** [comment]
OK will add it - working on it now.

**Comment by Robinlovelace** [comment]
Job done - looks tidy. Over to @masalmon ; )
