### ISSUE TITLE
Do not run code in vignette but show expected output

### ISSUE THREAD

**Issue by Robinlovelace** [osmdatar/osmdata#53]
Using the new reprex package for this: http://jennybc.github.io/reprex/

And linking to online plots like this: 

![image](https://cloud.githubusercontent.com/assets/1825120/23708182/fba4ed96-040c-11e7-90cd-3274d394030a.png)

**Comment by mpadge** [comment]
Now that is absolute gold!

**Comment by Robinlovelace** [comment]
This is a better plot - job done I think:

![image](https://cloud.githubusercontent.com/assets/1825120/23709309/e14e3390-0410-11e7-9b81-4433910fd237.png)

**Comment by Robinlovelace** [comment]
![image](https://cloud.githubusercontent.com/assets/1825120/23709339/01e75ae6-0411-11e7-8ba3-ef52f353a6fa.png)


Should be better..

**Comment by Robinlovelace** [comment]
Test:

**Comment by Robinlovelace** [comment]
![rplot](https://cloud.githubusercontent.com/assets/1825120/23709879/c98e2c2c-0412-11e7-86b8-1ffc95aab5a1.png)
