### ISSUE TITLE
error running overpass_sp()

### ISSUE THREAD

**Issue by Robinlovelace** [osmdatar/osmdata#58]
This is what I get when running the code, running from  https://github.com/cyipt/example-data 

```r
ct = osmdata_sp(doc = "../example-data/chapeltown-road/chapeltown.osm")
## q missing: osmdata object will not include query
## Error: cannot allocate vector of size 130331.5 Gb
```

**Comment by mpadge** [comment]
Yeah, i get a similar werge out - i'll look into it. Note that this all works:
```
x <- osmdata_sf (doc="../example-data/chapeltown-road/chapeltown.osm")
library (sf)
pts <- as (x$osm_points, "Spatial")
lns <- as (x$osm_lines, "Spatial")
pls <- as (x$osm_polygons, "Spatial")
```

**Comment by Robinlovelace** [comment]
Yes `osmdata_sf()` works like a dream and I'm gradually switching to it so no issue. Was just experimenting with good 'ol sp. Here's an idea: just convert the `sf` objects to sp for `osmdata_sp` - could save programmer and computing time I think, and keep the focus on `sf`.
