### ISSUE TITLE
get bbox from character string

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#6]
See comments on commits [here](https://github.com/osmdatar/osmdata/commit/4f3a1dc14b62722978044e791a2c37179eacfdeb) and [here](https://github.com/osmdatar/osmdata/commit/6b1c2c5b2ce61927118a96331fbe0e30dc751db7). Solution is from @hrbrmstr : Insert [`osm_search`](https://github.com/hrbrmstr/nominatim/blob/master/R/search.r) into `osmdata`.

**Comment by mpadge** [comment]
Relevant `tmap` code [here](https://github.com/mtennekes/tmap/blob/master/pkg/R/bb.R) and [here](https://github.com/mtennekes/tmap/blob/master/pkg/R/end_of_the_world.R) plus maybe[`_longlat`](https://github.com/mtennekes/tmap/blob/master/pkg/R/is_projected.R) plus `raster::extent`, `rgeos::gIntersection`

**Comment by Robinlovelace** [comment]
OK - want me to work on an implementation over the holidays or are you up for a 1st bash?

**Comment by mpadge** [comment]
I've gotta admit that that's pretty low down on my priorities at the mo, in spite of indubitable utility and all. Ergo: It'd be great if you could have a bash. The links above should contain all you need.

**Comment by mpadge** [comment]
Don't forget Bob's own [nominatim](http://github.com/hrbrmstr/nominatim)

**Comment by mpadge** [comment]
@Robinlovelace - thanks for the great work here. I've reopened it just to ask you for one further thing, and thought it might help you to go through this yourself: Can you please generate stubbed data for the [`getbb @example`](https://github.com/osmdatar/osmdata/blob/master/R/getbb.R#L55-L63) - see links in my brief comments on #23. I'd appreciate a second pair of eyes on my general approach here - it seems to me the best alternative while we all wait for Scott's [`vcr`](https://github.com/ropenscilabs/vcr) package, although this was before Gabor's contributions to the [extended discussions on these issues](https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460/2)

**Comment by Robinlovelace** [comment]
Yes but would like to chat about this first - how's tomorrow evening?
