### ISSUE TITLE
fix getbb()

### ISSUE THREAD

**Issue by mpadge** [osmdatar/osmdata#61]
@Robinlovelace here's one for ya: This should crash at some stage in the following way:
```
for (i in 1:100) q <- opq ("leeds")
# Error: lexical error: invalid char in json text.
#                                        <!DOCTYPE HTML PUBLIC "-//IETF/
#                      (right here) ------^
```
Could you catch these errors and spit out a simple "sorry, nominatim is broke; please try again" message?

**Comment by Robinlovelace** [comment]
Visual illustration of fix: working demo of results on the right (pubs in Poznan) and illustration of meaningful error message (left):

![image](https://cloud.githubusercontent.com/assets/1825120/26206525/58e18216-3be5-11e7-9145-4f805eede598.png)


Job done I'd say- clearly there's potential for caching etc but I think that's fine for now - it shouldn't be used for geocoding and the example shows how to select a custom url and an api key.

**Comment by mpadge** [comment]
That's a great fix - thanks so much for that! Nominatim will still stay switched off for tests, but those responses are enormously more useful than that previous junk it spat out about ill-formed json text :100:
