### ISSUE TITLE
Function to download osm data

### ISSUE THREAD

**Issue by Robinlovelace** [osmdatar/osmdata#8]
Sometimes you just want to download osm data and save it as a .osm file, e.g. to open in QGIS or JOSM. Is this possible?

**Comment by Robinlovelace** [comment]
Also I think it would be great to enable printing of overpass-turbo queries for testing, e.g.: http://overpass-turbo.eu/s/jM0

[out:json][timeout:25];
// gather results
(
  // query part for: “leisure=park”
  node["leisure"="park"]({{bbox}});
  way["leisure"="park"]({{bbox}});
  relation["leisure"="park"]({{bbox}});
);
// print results
out body;
>;
out skel qt;

**Comment by mpadge** [comment]
Second Q: Already implemented at [line#118 here](https://github.com/osmdatar/osmdata/blob/master/R/overpass_query.R) using [this class def](https://github.com/osmdatar/osmdata/blob/master/R/osmdata-class.R).

First Q: Not at the moment, but was possible in `osmdatar`, and i'll make sure i'll reinstate it.

**Comment by Robinlovelace** [comment]
Cheers for the feedback and let me know how I can help, although won't have real time until December. Will leave this open as a reminder. On Q2, how would you tell it to output that? Will aim to put in an `@example` into `overpass_query` docs when I find out.

**Comment by mpadge** [comment]
Re Q2 output: Former approach can be seen [here](https://github.com/osmdatar/osmdatar/blob/master/R/get-lines.R) - I used a `raw_data` parameter to optionally return the query output directly. This is of course massively against the whole discussion on type stability in [`sfr` issue#39](https://github.com/edzer/sfr/issues/39), and so maybe ought be rethunk ...

**Comment by Robinlovelace** [comment]
Yes indeed. I think we should aim for type stability also.

**Comment by mpadge** [comment]
Robin, what do you think of naming primary functions like this:
```
> osm_data_xml ()
> osm_data_csv ()
> osm_data_sp ()
> osm_data_sf ()
```
?
It would make downloading 'raw' (`xml`/`csv`) data pretty transparent, and solve #13 to boot. The results of `osm_data_xml` could optionally be fed to `osm_data_sp/sf` to avoid repeated downloading, and to enabled extraction of different objects from same raw data. Maybe most importantly: perfect type stability!

Or, given the package name, should these rather be called
```
> osmdata_xml ()
> osmdata_csv ()
> osmdata_sp ()
> osmdata_sf ()
```
?

**Comment by masalmon** [comment]
(I'm slowly reading all the issues :-)) Just a question regarding "to avoid repeated downloading", do you want to use the `memoise` package? Do you think it'll happen often that the same query is sent twice to the API?

**Comment by mpadge** [comment]
Thanks @masalmon - this issue has been resolved with #1

**Comment by mpadge** [comment]
Former `read_osm` now implemented as `osmdata_xml` and `osmdata_sp`, with the other two yet to come.

**Comment by mpadge** [comment]
A question for @Robinlovelace @masalmon:

* Do we really need `osmdata_csv()`?

Requesting `csv` output from overpass requires [specifying precisely which fields one desires](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Output_Format_.28out.29) - noting the abiding importance of the first statement there: ''Besides normal OSM field names ...''. Requesting `csv` requires users to know about OSM structure, in stark contrast to all other functions which require little or no knowledge. I suspect @hrbrmstr only put this there because that exact example happens to be in the overpass wiki, but i doubt such functionality would ever really be used.

My suggestion would be to implement `sf` and then use that as a way to get a straight `data.frame` which can then be export as `csv` if desired. Thoughts?

**Comment by masalmon** [comment]
Sounds good. I've only ever exported summary measures as csv (e.g. total distance) so I don't know how I would use this. If I were to export the data corresponding to a spatial object, I think I'd first wrangle the data.frame anyway.

**Comment by Robinlovelace** [comment]
- Regarding `osmdata_csv()` I agree: let's wait until `osmdata_sf()` is done and then just use that.
- Regarding the general approach, I think it's good. Using `osmdata_sp()` now and like the feel and extensibility of it - can't wait to try out `osmdata_sf()`.
- I would add for the binary format option `osmdata_pbf()` so people can save a compressed version of the raw osm data, which is very commonly used by OSM core users I think and would mean our work is useful for people wanting to go straight into a PostGIS db.

**Comment by mpadge** [comment]
`osmdata_pbf()` is a great idea, but i don't know how we'd easily achieve that in a platform independent way? The only simple way i know of is [`osmconvert`](https://wiki.openstreetmap.org/wiki/Osmconvert), but a no-go for osx. Do you know of any other ways to generate or convert `pbf`s?

**Comment by Robinlovelace** [comment]
osmosis looks pretty good: https://github.com/openstreetmap/osmosis - don't think it's an issue - could be the type of thing where it gives an error message like `Error: osmosis must be available to your system for this to work` then it's the user's responsibility to worry about OS specifics etc.

One for later I guess though...

**Comment by mpadge** [comment]
[`get-osmdata.R`](https://github.com/osmdatar/osmdata/blob/master/R/get-osmdata.R) now has `osmdata_xml`, `osmdata_sp` and `osmdata_sf`, which closes this issue. (`osmdata_sf` isn't finished, but will be done with #17).

**Comment by Robinlovelace** [comment]
This is awesome, great work @mpadge.
