### ISSUE TITLE
Error message when printing empty osmdata object

### ISSUE THREAD

**Issue by Robinlovelace** [osmdatar/osmdata#9]
Example:

```r
origins = dl_origins(bb)
q = osmdata::opq(bbox = bb) %>% 
  osmdata::add_feature("place", "*")
origins = osmdata::overpass_query(q)
origins
```
```
$osm_lines
Error in signif(sapply(coordinates(x), function(x) x[[1]][1, ]), digits = digits) : 
  non-numeric argument to mathematical function
```

It's probably not a meaningful query but think the error message could be a little more informative at least!

**Comment by mpadge** [comment]
Thanks Robin, but that's one i beat you to [29 days earlier it seems](https://github.com/osmdatar/osmdata/issues/4), and simply requires extending [these lines](https://github.com/osmdatar/osmdata/blob/master/R/osmdata-class.R#L33-L35) with an `else` (`== is.null`). I've been a bit pressed for time to work on this lately, but intend to find more asap. First task is nevertheless hard-coding construction of `sf` objects (that is, without a direct `sf` dependency and all that that entails), but that's proving a little time consuming - i'm trying to do it 'properly', by comparing built sizes with an without `sf` dependency blah blah ... i'll get on to it in the next coupla weeks.

**Comment by Robinlovelace** [comment]
Ah apologies for duplicate message.
